### ISSUE TITLE
.gitconfig is owned by root

### ISSUE THREAD

**Issue by seanknox** [boxen/puppet-git#53]
The created `.gitconfig` is owned by root when it should be owned by the local user.

**Comment by sebroeder** [comment]
I cannot reproduce this issue here with puppet-git `2.7.6`:

```bash
$ ls -al ~/.gitconfig 
-rw-r--r--  1 sebroeder  staff  231 Apr  3 23:42 .gitconfig
```

**Comment by seanknox** [comment]
Thanks @sebroeder, going to close this one.
