### ISSUE TITLE
Error: git 2.2.1 already installed

### ISSUE THREAD

**Issue by toolbear** [boxen/puppet-git#56]
Bootstrap failing with latest boxen on pristine OS X 10.10 install:

```console
Error: /Stage[main]/Git/Package[boxen/brews/git]/ensure: change from 2.2.1 to 2.1.4-boxen1 failed: Could not update: Execution of 'brew boxen-upgrade boxen/brews/git' returned 1: Error: git 2.2.1 already installed
```

Which cascades to

```console
Warning: /Stage[main]/Boxen::Repo/Exec[clone /opt/boxen/repo]: Skipping because of failed dependencies
```

Open new Terminal when bootstrapping finishes and unsurprisingly:

```console
Last login: Tue Jan  6 22:22:53 on ttys001
Boxen could not load properly!
resolute-tumbrel-6808:~ toolbear$ 
```

## Steps to Reproduce

1. clean install Yosemite (10.10.1)
2. install Xcode from App Store
3. bootstrap boxen (boxen/our-boxen@45fa8853) via curl/bash command provided by boxen-web (boxen/boxen-web@adea460d)

Minimal changes in my toolbear-boxen (our-boxen fork):

* `/usr/local` for `homebrew_root`
* a package (tree) and two apps (Dropbox, 1Password) in `hiera/users/toolbear.yaml`

**Comment by toolbear** [comment]
Trying again with boxen's stock `homebrew_root` (that the only provided example of a custom fact is changing brew to `/usr/local` is a special kind of trap :unamused:).

## Cleanup

1. `rm -rf /usr/local`
2. `rm -rf /opt/boxen`

## Workaround

1. run boxen-web bootstrap script
2. `brew rm git`
3. run boxen-web bootstrap script again
4. proceed as usual

```console
$ curl -s https://<redacted>.herokuapp.com/script/772c8f01.sh > /tmp/install-boxen; bash /tmp/install-boxen
…
Error: Could not update: Execution of 'brew boxen-upgrade boxen/brews/git' returned 1: Error: git 2.2.1 already installed
Wrapped exception:
Execution of 'brew boxen-upgrade boxen/brews/git' returned 1: Error: git 2.2.1 already installed
Error: /Stage[main]/Git/Package[boxen/brews/git]/ensure: change from 2.2.1 to 2.1.4-boxen1 failed: Could not update: Execution of 'brew boxen-upgrade boxen/brews/git' returned 1: Error: git 2.2.1 already installed
Notice: /Stage[main]/Hub/Package[hub]/ensure: created
Notice: /Stage[main]/Boxen::Repo/Exec[clone /opt/boxen/repo]: Dependency Package[boxen/brews/git] has failures: true
Warning: /Stage[main]/Boxen::Repo/Exec[clone /opt/boxen/repo]: Skipping because of failed dependencies
Notice: /Stage[main]/Boxen::Bin/File[/opt/boxen/bin/boxen]: Dependency Package[boxen/brews/git] has failures: true
Warning: /Stage[main]/Boxen::Bin/File[/opt/boxen/bin/boxen]: Skipping because of failed dependencies

$ brew rm git
$ curl -s https://<redacted>.herokuapp.com/script/772c8f01.sh > /tmp/install-boxen; bash /tmp/install-boxen
…
You're good to go! Make sure to source /opt/boxen/env.sh in your
shell config if you want all the good stuff to work.

$ source /opt/boxen/env.sh
$ boxen
boxen
--> Preparing to auto-update...
--> Complete! Nothing new from upstream.
Fact file /opt/boxen/repo/facts.d/example.yaml was parsed but returned an empty data set
Notice: Compiled catalog for resolute-tumbrel-6808.local in environment production in 4.37 seconds

# open new terminal
$ boxen
boxen
--> Preparing to auto-update...
--> Complete! Nothing new from upstream.
Fact file /opt/boxen/repo/facts.d/example.yaml was parsed but returned an empty data set
Notice: Compiled catalog for resolute-tumbrel-6808.local in environment production in 4.37 seconds
```

**Comment by dgoodlad** [comment]
@toolbear The `/usr/local` homebrew fact is something brand new; it's the only example because it's the only thing that has required that functionality so far.

Without seeing your entire boxen repo, your personal manifest, your Puppetfile, I have very little to go on here. I suspect that one of your homebrew packages installs git as a dependency, and that it's doing that far too early. If you can identify which package is pulling it in, you can specify an explicit relationship between the `boxen/brews/git` package and the troublesome one using a resource collector:

```puppet
Package <| name == 'boxen/brews/git' |> {
  before => Package['foo'],
}
```

**Comment by rafaelfranca** [comment]
I know brew-cask installs git as dependency. But I have not saw this
failure yet. My boxen repository just downgrade the git version to the
specified in my repository

**Comment by mikemcquaid** [comment]
@rafaelfranca It doesn't (using Homebrew anyway).

**Comment by toolbear** [comment]
dgoodlad et al., because I probably seemed ungrateful, thanks for all the work. Boxen has improved since I was last using it routinely. Many personal manifests can now be trashed in favor of a hiera config, for instance.

@dgoodlad thanks for the explanation and tip. I'm not passionate about `/usr/local`; I thought using it might avoid problems. Previously homebrew under `/opt/boxen` worked flawlessly, so I'll stick with that for now.

@rafaelfranca are you bootstrapping from a pristine OS X install?

**Comment by philduffy** [comment]
Just a note, I hit this with a fresh install of OS X yesterday (though it was git 2.2.2). I'll be installing on another fresh machine today and I'll report back if I hit it again.

I was able to resolve with a `brew rm git` and then running the script again.

**Comment by mikemcquaid** [comment]
As a more general issue perhaps to be filed elsewhere: Boxen should probably handle the "trying to upgrade to an older version" issue a bit better.

**Comment by mikemcquaid** [comment]
This should be fixed now due to https://github.com/Homebrew/homebrew/pull/36699/files

**Comment by jbcpollak** [comment]
I hit this today with a brand new Mac:

```
Error: Could not update: Execution of 'brew boxen-upgrade boxen/brews/git' returned 1: Error: git 2.3.7 already installed
Wrapped exception:
Execution of 'brew boxen-upgrade boxen/brews/git' returned 1: Error: git 2.3.7 already installed
Error: /Stage[main]/Git/Package[boxen/brews/git]/ensure: change from 2.3.7 to 2.3.0 failed: Could not update: Execution of 'brew boxen-upgrade boxen/brews/git' returned 1: Error: git 2.3.7 already installed
```

I just updated my boxen repository with the latest upstream our-boxen version, but that doesn't seem to help.

I'm not sure how @mikemcquaid 's fix will help, my Puppetfile has this:

    github "homebrew",    "1.11.2"

Should I upgrade to a newer version of https://github.com/boxen/puppet-homebrew?

**Comment by mikemcquaid** [comment]
That may fix it, yeh.

**Comment by salimane** [comment]
I've just hit this after doing a ``brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup``

**Comment by mikemcquaid** [comment]
This will probably be fixed after https://github.com/Homebrew/homebrew/pull/40096 is merged and definitely after https://github.com/Homebrew/homebrew/pull/39524 is merged.

**Comment by mikemcquaid** [comment]
This is fixed by upgrading `puppet-homebrew` to the new 1.12.1 release: https://github.com/boxen/puppet-homebrew/releases/tag/1.12.1
