### ISSUE TITLE
Tagged releases 2.7.91 and 2.7.92 are very confusing

### ISSUE THREAD

**Issue by indirect** [boxen/puppet-git#73]
The latest tagged release is 2.7.11, so it's really confusing that there are (very old) tagged releases named 2.7.91 and 2.7.92. :/

**Comment by ajb** [comment]
Just ran into this as well. Would be great if these tags could be removed or a new tag could be added.

**Comment by jacobbednarz** [comment]
Sorry for the confusion. I believe this is now fixed (per my tagging) but feel free to sing out if it is still an issue.
