### ISSUE TITLE
Update git to at least 2.13.5

### ISSUE THREAD

**Issue by mootpointer** [boxen/puppet-git#87]
Ya'll probably know about this, but git 2.13.5 is a security patch for a [nasty vulnerability](http://marc.info/?l=git&m=150238802328673&w=2). It'd be great to get the version updated fairly rapidly.

I'm happy to help, but I'm not quite sure on where to start.

**Comment by jacobbednarz** [comment]
Thanks for the heads up! If you want to take a stab at this, I've done this a couple of times (#86) is the latest one.

Basically, see what the upstream Homebrew formula looks like and drop it into the `puppet-git` repository. Might need some small tweaks but pretty straight forward stuff.

**Comment by mootpointer** [comment]
I'm assuming that in keeping with the principals, you'd go with 2.13.5 and not 2.14.1?

**Comment by jacobbednarz** [comment]
2.14.x is fine 👍

**Comment by jacobbednarz** [comment]
Due to the security nature of this, I've opened #88 to address it. Feel free to review it and let me know if anything looks out of place. Perhaps we can line you up for the line one? :smile:

**Comment by mootpointer** [comment]
Looks good here. Sorry I couldn't get to it today – I've been a bit swamped on other things.

**Comment by jacobbednarz** [comment]
No worries at all! Thanks for the nudge ❤️
